<a href="https://colab.research.google.com/github/nankris/TensorFlow-basics/blob/master/tensorflow_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
print(tf.version)
#we are using version 2

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [0]:
#creating different sensors
strng=tf.Variable("string variable",tf.string)
numbr=tf.Variable(123,tf.int16)
flting=tf.Variable(1.23,tf.float64)
#rank 0 also known as scalar

In [0]:
print(strng)
print(numbr)
print(flting)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'string variable'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.23>


In [0]:
r0_tensor=tf.Variable("Test",tf.string)
r1_tensor=tf.Variable(["Test","test2"],tf.string)
r2_tensor=tf.Variable([["test","ok"],["test","yes"]],tf.string)

In [0]:
tf.rank(r0_tensor) #this is a method

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [0]:
tf.rank(r1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [0]:
tf.rank(r2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [0]:
r0_tensor.shape

TensorShape([])

In [0]:
r1_tensor.shape

TensorShape([2])

In [0]:
r2_tensor.shape

TensorShape([2, 2])

In [0]:
#Changing shapes

In [0]:
tensor1=tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [0]:
tensor2=tf.ones([1,2])
print(tensor2)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)


In [0]:
tensor3=tf.ones([4])
print(tensor3)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)


In [0]:
tensor4=tf.ones(4)
print(tensor4)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)


In [0]:
tensor4=tf.ones(1,2)
print(tensor4)

tf.Tensor([1.], shape=(1,), dtype=float64)


In [0]:
tensor_reshape=tf.reshape(tensor1,[2,3,1]) #we are having 2 lists and each list is 3 rows and 1 column
tensor_reshape2=tf.reshape(tensor1,[3,-1]) #-1 tells the tensor to calculate the size of the dimension in that place

In [0]:
print(tensor1)
print(tensor_reshape)
print(tensor_reshape2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
